
export const START_HUB_CONNECTION = "START_HUB_CONNECTION";
export const STOP_HUB_CONNECTION = "STOP_HUB_CONNECTION";
export const CHANGE_HUB_URL = "CHANGE_HUB_URL";
export const SET_CONNECTION_STATUS = "SET_CONNECTION_STATUS";