
export const START_HUB_CONNECTION = "START_HUB_CONNECTION";
export const STOP_HUB_CONNECTION = "STOP_HUB_CONNECTION";
export const CHANGE_HUB_URL = "CHANGE_HUB_URL";
export const SET_CONNECTION_STATUS = "SET_CONNECTION_STATUS";

export const SET_INVOKE_METHOD_NAME = "SET_INVOKE_METHOD_NAME";
export const ADD_INVOKE_METHOD = "ADD_INVOKE_METHOD";
export const DELETE_INVOKE_METHOD = "DELETE_INVOKE_METHOD";
export const ADD_ARG_TO_INVOKE_METHOD = "ADD_ARG_TO_INVOKE_METHOD";